# SPDX-License-Identifier: AGPL-3.0-or-later
"""initial

Revision ID: 5adfdbbc6e70
Revises: 
Create Date: 2026-05-12 22:24:04.050745

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5adfdbbc6e70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'date', name='uq_exchange_rate')
    )
    op.create_index(op.f('ix_exchange_rates_date'), 'exchange_rates', ['date'], unique=False)
    op.create_table('products',
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('currencies', sa.String(length=100), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['products.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_asset_price_ticker_date')
    )
    op.create_index(op.f('ix_asset_prices_date'), 'asset_prices', ['date'], unique=False)
    op.create_index(op.f('ix_asset_prices_ticker'), 'asset_prices', ['ticker'], unique=False)
    op.create_table('daily_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_eur', sa.Float(), nullable=False),
    sa.Column('offensive_eur', sa.Float(), nullable=False),
    sa.Column('defensive_eur', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_snapshot')
    )
    op.create_index(op.f('ix_daily_snapshots_date'), 'daily_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_daily_snapshots_user_id'), 'daily_snapshots', ['user_id'], unique=False)
    op.create_table('monthly_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_eur', sa.Float(), nullable=False),
    sa.Column('offensive_eur', sa.Float(), nullable=False),
    sa.Column('defensive_eur', sa.Float(), nullable=False),
    sa.Column('contributions_eur', sa.Float(), nullable=False),
    sa.Column('performance_pct', sa.Float(), nullable=False),
    sa.Column('performance_index', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_monthly_snapshot')
    )
    op.create_index(op.f('ix_monthly_snapshots_user_id'), 'monthly_snapshots', ['user_id'], unique=False)
    op.create_table('pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('target_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_pool_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('value_eur', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['daily_snapshot_id'], ['daily_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_pool_snapshots_daily_snapshot_id'), 'daily_pool_snapshots', ['daily_snapshot_id'], unique=False)
    op.create_table('monthly_pool_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('value_eur', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['monthly_snapshot_id'], ['monthly_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_pool_snapshots_monthly_snapshot_id'), 'monthly_pool_snapshots', ['monthly_snapshot_id'], unique=False)
    op.create_table('pool_products',
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['products.ticker'], ),
    sa.PrimaryKeyConstraint('pool_id', 'ticker')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('unit_price_eur', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('total_amount_eur', sa.Float(), nullable=False),
    sa.Column('balance_currency', sa.Float(), nullable=True),
    sa.Column('balance_eur', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['products.ticker'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('pool_products')
    op.drop_index(op.f('ix_monthly_pool_snapshots_monthly_snapshot_id'), table_name='monthly_pool_snapshots')
    op.drop_table('monthly_pool_snapshots')
    op.drop_index(op.f('ix_daily_pool_snapshots_daily_snapshot_id'), table_name='daily_pool_snapshots')
    op.drop_table('daily_pool_snapshots')
    op.drop_table('pools')
    op.drop_index(op.f('ix_monthly_snapshots_user_id'), table_name='monthly_snapshots')
    op.drop_table('monthly_snapshots')
    op.drop_index(op.f('ix_daily_snapshots_user_id'), table_name='daily_snapshots')
    op.drop_index(op.f('ix_daily_snapshots_date'), table_name='daily_snapshots')
    op.drop_table('daily_snapshots')
    op.drop_index(op.f('ix_asset_prices_ticker'), table_name='asset_prices')
    op.drop_index(op.f('ix_asset_prices_date'), table_name='asset_prices')
    op.drop_table('asset_prices')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_index(op.f('ix_exchange_rates_date'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
