# SPDX-License-Identifier: AGPL-3.0-or-later
"""add_cash_balance_eur_to_accounts

Revision ID: c65f3ee73576
Revises: 5adfdbbc6e70
Create Date: 2026-05-14 06:26:16.084188

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c65f3ee73576'
down_revision: Union[str, None] = '5adfdbbc6e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('cash_balance_eur', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'cash_balance_eur')
    # ### end Alembic commands ###
